### ISSUE TITLE
Having issue installing 0.1.0

### ISSUE THREAD

**Issue by huiyuan** [ahmadsoe/ember-highcharts#17]
I updated my ember-cli to 0.2.0 and tried to reinstall highcharts 0.1.0 but got the following error when running ember server. My ember-cli app path is /Users/hiyang/me-share/test-app.

ENOENT, no such file or directory '/Users/hiyang/me-share/test-app/node_modules/ember-highcharts/bower_components/'
Error: ENOENT, no such file or directory '/Users/hiyang/me-share/test-app/node_modules/ember-highcharts/bower_components/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:765:18)
    at /Users/hiyang/me-share/test-app/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:32:21
    at Array.map (native)
    at mergeRelativePath (/Users/hiyang/me-share/test-app/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:30:29)
    at /Users/hiyang/me-share/test-app/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:23:5
    at lib$rsvp$$internal$$tryCatch (/Users/hiyang/me-share/test-app/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/hiyang/me-share/test-app/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/hiyang/me-share/test-app/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/Users/hiyang/me-share/test-app/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)

I installed by using "ember install:addon ember-highcharts", any ideas of how to resolve this?

**Comment by ahmadsoe** [comment]
Just released a new version [v0.1.1](https://github.com/ahmadsoe/ember-highcharts/releases/tag/v0.1.1), should working now.
