### ISSUE TITLE
ember-cli 0.1.15 - Unexpected token (6:5)

### ISSUE THREAD

**Issue by mszoernyi** [ahmadsoe/ember-highcharts#18]
I'm still debugging but maybe someone has a clue already. I upgraded to ember-cli 0.1.15 and ran `ember install:addon ember-highcharts`

Afterwards I tried to `build` the project which fails. Without ember-highcharts everything works fine. 

```bash
$ ember build
version: 0.1.15
Could not find watchman, falling back to NodeWatcher for file system events
Build failed.
File: ember-highcharts/components/high-charts
Unexpected token (6:5)
SyntaxError: Unexpected token (6:5)
  at raise (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:333:15)
  at unexpected (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1366:5)
  at parseIdent (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2471:7)
  at parsePropertyName (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2250:78)
  at parseObj (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2225:9)
  at parseExprAtom (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2136:14)
  at parseVar (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1875:57)
  at parseVarStatement (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1763:5)
  at parseStatement (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1569:47)
  at parseTopLevel (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1526:18)
  at Object.exports.parse (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:48:12)
  at getStandaloneModule (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/dist/esperanto.js:503:14)
  at Class.toFormat (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/dist/esperanto.js:2538:9)
  at Class.module.exports.CachingWriter.extend._transpileThroughCache (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/index.js:230:22)
  at Class.module.exports.CachingWriter.extend._handleFile (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/index.js:202:22)
  at Class.<anonymous> (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/index.js:185:16)
  at Array.forEach (native)
  at Class.module.exports.CachingWriter.extend._updateEachFile (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/index.js:183:8)
  at Class.module.exports.CachingWriter.extend.updateCache (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/index.js:141:74)
  at /home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/broccoli-caching-writer/index.js:92:34
  at lib$rsvp$$internal$$tryCatch (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
  at lib$rsvp$$internal$$publish (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
  at Object.lib$rsvp$asap$$flush [as _onImmediate] (/home/mike/projects/remerge/ui/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
  at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by huiyuan** [comment]
@mszoernyi, could you please try to update ember-cli to 0.2.0?

**Comment by mszoernyi** [comment]
Yeah thats an issue for us right now. There are some dependencies which are still not compatible with 0.2.0. 

Seems like I need postpone this topic

**Comment by poteto** [comment]
@mszoernyi If you can't do the full upgrade to `0.2.0`, change `ember-cli-6to5` to `ember-cli-babel`. That should fix it.

**Comment by ahmadsoe** [comment]
> Seems like I need postpone this topic

If you're still having problems feel free to reopen this issue.

**Comment by mszoernyi** [comment]
@poteto Good idea. But ember-cli itself depends on `0.2.0`

**Comment by trentmwillis** [comment]
@mszoernyi 6to5 has been renamed [Babel](https://babeljs.io/blog/2015/02/15/not-born-to-die/), so newer version of Ember-CLI use `ember-cli-babel`.

**Comment by mszoernyi** [comment]
@trentmwillis I know but the issue is I can't upgrade to 0.2.0 which uses `babel` older versions depend on `6to5`. I will finish my stuff and patch the other dependencies which hinder me upgrading. Thanks for the help.
